# Generated by Django 3.1.1 on 2020-09-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200930_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='experiences',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='about',
            name='short_description',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
