# Generated by Django 3.1.1 on 2020-09-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200930_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_title', models.TextField(default='SOME STRING')),
                ('skills', models.TextField(default='SOME STRING')),
            ],
        ),
    ]
