# Generated by Django 3.1.1 on 2020-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200930_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Work description'),
        ),
    ]
