# Generated by Django 3.1.1 on 2020-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recentwork_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='description',
            field=models.TextField(default='SOME STRING', verbose_name='Work description'),
        ),
    ]
