# Generated by Django 3.1.1 on 2020-10-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_techlogos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techlogos',
            options={'verbose_name': 'Tech Logo', 'verbose_name_plural': 'Tech Logos'},
        ),
        migrations.AlterField(
            model_name='techlogos',
            name='image',
            field=models.ImageField(upload_to='logos'),
        ),
    ]
