# Generated by Django 3.1.1 on 2020-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201001_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='code',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='demo',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='demo'),
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='site',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
