# Generated by Django 3.1.1 on 2020-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201002_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='modal',
            field=models.TextField(blank=True, verbose_name='Work experience'),
        ),
    ]
