# Generated by Django 3.1.1 on 2020-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201002_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='modal')),
                ('comapny', models.TextField(blank=True, verbose_name='company')),
                ('position', models.TextField(blank=True, verbose_name='position')),
                ('date', models.CharField(max_length=100, verbose_name='date')),
                ('responsibilites', models.TextField(blank=True, verbose_name='responsibilities')),
            ],
            options={
                'verbose_name': 'Modal',
                'verbose_name_plural': 'Modals',
            },
        ),
        migrations.RemoveField(
            model_name='journey',
            name='modal',
        ),
    ]
