# Generated by Django 3.1.1 on 2020-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201002_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modal',
        ),
        migrations.AddField(
            model_name='journey',
            name='modal',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='description',
            field=models.TextField(default='SOME STRING', verbose_name='Work description'),
        ),
    ]
