# Generated by Django 3.1.1 on 2020-10-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201010_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding_languages', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Coding language',
                'verbose_name_plural': 'Coding languages',
            },
        ),
        migrations.CreateModel(
            name='CodingLanguagesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('CodingLanguages', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.codinglanguages')),
            ],
        ),
        migrations.RemoveField(
            model_name='skillsimage',
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='SkillsImage',
        ),
    ]
