# Generated by Django 3.1.1 on 2020-11-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201102_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.TextField(blank=True, verbose_name='job description')),
            ],
            options={
                'verbose_name': 'Duty',
                'verbose_name_plural': 'Duties',
            },
        ),
        migrations.AlterField(
            model_name='journey',
            name='job_title',
            field=models.TextField(blank=True, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='job_title2',
            field=models.TextField(blank=True, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='job_title3',
            field=models.TextField(blank=True, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='job_title4',
            field=models.TextField(blank=True, verbose_name='job title'),
        ),
    ]
