# Generated by Django 3.1.1 on 2020-11-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201102_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duties',
            options={},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={},
        ),
        migrations.RemoveField(
            model_name='journey',
            name='company_image',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='date',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='image',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='job_date',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='job_title',
        ),
        migrations.AddField(
            model_name='journey',
            name='duties',
            field=models.ManyToManyField(to='core.Duties'),
        ),
        migrations.AlterField(
            model_name='duties',
            name='duty',
            field=models.CharField(max_length=100),
        ),
    ]
