# Generated by Django 3.1.1 on 2020-11-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201102_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duties',
            name='duty',
            field=models.CharField(choices=[], default='Em', max_length=200),
        ),
    ]
