# Generated by Django 3.1.1 on 2020-11-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201102_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duties',
            name='duty',
            field=models.CharField(max_length=100, verbose_name='duty'),
        ),
    ]
