# Generated by Django 3.1.1 on 2020-11-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201102_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duties',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='duties',
        ),
        migrations.AddField(
            model_name='duties',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='duties',
            name='journey',
            field=models.ManyToManyField(blank=True, related_name='duties', to='core.Journey'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='company_image',
            field=models.ImageField(upload_to='journey', verbose_name='company image'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='image',
            field=models.ImageField(upload_to='journey'),
        ),
    ]
