# Generated by Django 3.1.1 on 2020-11-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20201102_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duties',
            name='journey',
        ),
        migrations.AddField(
            model_name='journey',
            name='duties',
            field=models.ManyToManyField(blank=True, related_name='duties', to='core.Duties'),
        ),
    ]
