# Generated by Django 3.1.1 on 2020-11-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201102_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='company_image2',
            field=models.ImageField(blank=True, upload_to='journey', verbose_name='company image'),
        ),
        migrations.AddField(
            model_name='journey',
            name='company_image3',
            field=models.ImageField(blank=True, upload_to='journey', verbose_name='company image'),
        ),
        migrations.AddField(
            model_name='journey',
            name='company_name2',
            field=models.TextField(blank=True, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='journey',
            name='company_name3',
            field=models.TextField(blank=True, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='journey',
            name='duties2',
            field=models.ManyToManyField(blank=True, related_name='duties2', to='core.Duties'),
        ),
        migrations.AddField(
            model_name='journey',
            name='duties3',
            field=models.ManyToManyField(blank=True, related_name='duties3', to='core.Duties'),
        ),
        migrations.AddField(
            model_name='journey',
            name='job_date2',
            field=models.CharField(blank=True, max_length=100, verbose_name='job date'),
        ),
        migrations.AddField(
            model_name='journey',
            name='job_date3',
            field=models.CharField(blank=True, max_length=100, verbose_name='job date'),
        ),
        migrations.AddField(
            model_name='journey',
            name='job_title2',
            field=models.TextField(blank=True, verbose_name='job title'),
        ),
        migrations.AddField(
            model_name='journey',
            name='job_title3',
            field=models.TextField(blank=True, verbose_name='job title'),
        ),
    ]
