# Generated by Django 3.1.1 on 2020-11-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20201103_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='company_page',
            field=models.TextField(blank=True, verbose_name='company page'),
        ),
        migrations.AddField(
            model_name='journey',
            name='company_page2',
            field=models.TextField(blank=True, verbose_name='company page'),
        ),
        migrations.AddField(
            model_name='journey',
            name='company_page3',
            field=models.TextField(blank=True, verbose_name='company page'),
        ),
    ]
