# Generated by Django 3.1.1 on 2020-11-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201105_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='work_description',
            field=models.TextField(blank=True, verbose_name='Work responsibilities'),
        ),
    ]
